---
abstract: 'CPAN Meta DB source implementation'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPANPLUS-Internals-Source-CPANMetaDB
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  CPANPLUS::Internals::Source::CPANMetaDB:
    file: lib/CPANPLUS/Internals/Source/CPANMetaDB.pm
    version: 0.02
  CPANPLUS::Internals::Source::CPANMetaDB::HTTP:
    file: lib/CPANPLUS/Internals/Source/CPANMetaDB/HTTP.pm
    version: 0.02
  CPANPLUS::Internals::Source::CPANMetaDB::Tie:
    file: lib/CPANPLUS/Internals/Source/CPANMetaDB/Tie.pm
    version: 0.02
requires:
  CPANPLUS: 0.9001
  File::Fetch: 0
  File::Spec: 0
  Locale::Maketext::Simple: 0
  Module::Load::Conditional: 0
  Params::Check: 0
  Parse::CPAN::Meta: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/cpanplus-internals-source-cpanmetadb/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/cpanplus-internals-source-cpanmetadb.git
version: 0.02
